spring.application.name: stock

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/stock_example?serverTimezone=KST&allowMultiQueries=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 40
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE