spring.application.name: hello-spring-batch

spring:
  profiles:
    active: maria

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded

# 배치 자동 실행옵션 Off
    job:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: maria

  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/springbatch
      username: root
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always
#    job:
#      enabled: true
#      enabled: true # 멀티 잡을 사용할 경우에는 실행을 하면서 동시에 실행시키면 안된다....ㅋㅋㅋ;;; 아하
#      name: parameterJob
#  main:
#    allow-bean-definition-overriding: true

