spring.application.name: hello-spring-batch

spring:
  profiles:
    active: maria


---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: maria

  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/springbatch
      username: root
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always