spring:
  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:jdbc;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:


logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
#       Rollback여부 확인을 위한 Log 추가
        jdbc:
          dataSource:
            DataSourceTransactionManager: DEBUG
        orm:
          jpa:
            JpaTransactionManager: DEBUG
      hibernate:
        resource:
          transaction: DEBUG
        SQL: DEBUG
